apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentication-service.fullname" . }}
  labels:
    {{- include "authentication-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9001
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "authentication-service.selectorLabels" . | nindent 4 }}
