import os

from dotenv import load_dotenv

load_dotenv(dotenv_path=".env.test")

SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT") or "local"
ENVIRONMENT = os.environ.get("ENVIRONMENT")
LOG_LEVEL = os.environ.get("LOG_LEVEL")
SERVICE_NAME = os.environ.get("SERVICE_NAME")
APP_PORT = os.environ.get("UVICORN_PORT") or 8001
JWT_AUTHENTICATION_SECRET = os.environ.get("JWT_AUTHENTICATION_SECRET")
JWT_AUTHENTICATION_EXPIRY_SECRETS = int(
    os.environ.get("JWT_AUTHENTICATION_EXPIRY_SECRETS")
)
EMAIL_VERIFICATION_TYPES = ["CONFIRM_ACCOUNT_VERIFICATION"]
JWT_CONFIRM_ACCOUNT_SECRET = os.environ.get("JWT_CONFIRM_ACCOUNT_SECRET")
JWT_CONFIRM_ACCOUNT_EXPIRY_SECONDS = int(
    os.environ.get("JWT_CONFIRM_ACCOUNT_EXPIRY_SECONDS")
)
