@startuml
title Create Confirm Account Token Activity Diagram

:Request;
note
    POST - /jwt/confirm-account
end note

:Authentication Service;

skinparam ActivityDiamondBackgroundColor orchid
skinparam ConditionalEndStyle hline
switch (JWT_ERROR?)
case (no)
    #limegreen:Return 200;
    kill;
case (KeyError)
    #tomato:Return 400;
    kill;
case (TypeError)
    #tomato:Return 400;
    kill;
case (JWTError)
    #tomato:Return 400;
    kill;
endswitch

@enduml
