import os

from dotenv import load_dotenv

load_dotenv()


HTTP_STATUS_CODE_EXPIRED_TOKEN = 498

AWS_REGION = os.environ.get("AWS_REGION")
SENTRY_ENVIRONMENT = os.environ.get("SENTRY_ENVIRONMENT") or "local"
SENTRY_DSN = os.environ.get("SENTRY_DSN")
SENTRY_TRACES_SAMPLE_RATE = float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE"))
SENTRY_PROFILES_SAMPLE_RATE = float(os.environ.get("SENTRY_PROFILES_SAMPLE_RATE"))
SENTRY_SAMPLE_RATE = int(os.environ.get("SENTRY_SAMPLE_RATE"))

ENVIRONMENT = os.environ.get("ENVIRONMENT")
LOG_LEVEL = os.environ.get("LOG_LEVEL")
SERVICE_NAME = os.environ.get("SERVICE_NAME")
APP_PORT = os.environ.get("UVICORN_PORT") or 8001
JWT_SECRET = os.environ.get("JWT_SECRET")
JWT_EXPIRY_SECONDS = int(os.environ.get("JWT_EXPIRY_SECONDS"))

EMAIL_VERIFICATION_TYPES = ["CONFIRM_ACCOUNT_VERIFICATION"]
JWT_SECRET_CONFIRM_ACCOUNT = os.environ.get("JWT_SECRET_CONFIRM_ACCOUNT")
JWT_EXPIRY_SECONDS_CONFIRM_ACCOUNT = int(
    os.environ.get("JWT_EXPIRY_SECONDS_CONFIRM_ACCOUNT")
)

METRIC_ENDPOINTS = ["/healthz", "/api/jwt"]
