jwtAuthenticationSecret: ENC[AES256_GCM,data:EDJ0CfaTCTRvNm7K0aQVYgKgy7btU058i9AOMfMgW8u5zihp,iv:9pAfanbOxJQ9qOpJhX/W3AOv6tUgHSqfC8c/mFxFTl4=,tag:aK6n1imHgk+dM3FMzX0MGA==,type:str]
jwtAuthenticationExpirySeconds: ENC[AES256_GCM,data:AJyy2A==,iv:rFPDwebMSkVZydHgZB7qSrbF4V/WsuBGdQbZXqGIEMs=,tag:6mv7uF7FK50TsTsC0iLpzA==,type:int]
jwtConfirmAccountSecret: ENC[AES256_GCM,data:TSY7UHvxRm8LWDI3/7T/8hWHUf6eK5y5VOOpnT8Lkf4k+CEiR7il,iv:FCGXIPqIwEXeFjnV+157Q1MB9UrJK1B/qJ1e4knOBbs=,tag:eEieGLsMRkUWRzaKeInVAA==,type:str]
jwtConfirmAccountExpirySeconds: ENC[AES256_GCM,data:AoHNEA==,iv:UoIzkhuowtyo21/29Pd0KfzoIyhb6LiuVpM2uuu6Osg=,tag:brqeZHZ49bZaY2RG4rK6ZQ==,type:int]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-08-17T12:29:12Z"
  mac: ENC[AES256_GCM,data:0QdjQq4P11wqLN0F8BNmEIgRBNk2+tSXknUxZMYRQSJV7qVefeefiB9m1hMXyqD8Wd3iBz2Kyp9/0X1tENvtQ9IaHewfoHaye0nkN7pwagagRReG2n6xueSuQ/Wm9Xn4K8uTr8PfuJykQaPngL4lOzVyDoGid4cprXRWXkX8IOw=,iv:8S3zDCwvCMJz0odcG3gs8J5nlmZbiJrv1592RoBL7MY=,tag:9Ko2rLmcjn+vfFdsd+/7fg==,type:str]
  pgp:
    - created_at: "2025-08-17T12:29:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA0YyKT4zfWjNARAAoAz2wUtfo97BSuPmQDtV2No+z/KnBzLmBaT6VoBAdCGl
        8RxEFgavLRm5NTkgRThZrY7S025PNKF+ERNmxD1tovlflOvfECs0d2dYjXGu35IM
        oHunLnuLKNIbIVsOnu9ge0hBbclxleaxJtHbjYmsnKCobMe0Oou9RGVo/T26fTNj
        bitWMAiiscNG6zRnlt31WbPABonM2G//Cergxpt73XfY2/rnXHnu1gOQNMtCzzz9
        gEVmEJkLM+lwOSMmf1zFNZKTYgEPKhnQUSft2ETTQkoV3AsVMOg+AU6KKhuhFZAK
        HxiQieDY+gwxZ54zb6jXTDmtFr/6NmEVxkcxlbFJbUrbPCvYHeJ7M+Oa1y6Sq8EC
        ADkOHSzERSriKB5/vp3+VFCgBfBDzA1aJM3gqHHH74eOnygkREVuX55dbEuYg9bP
        i4ui3k/9OZBKYLl5+uP/ofQmbXv98U5cyoSpzd5mDAhHBit9mpuJadEhrU6vU++w
        okx6N/8xBmfkAlqkz+1b8fSHYIyyb1NGgiOReSq7MYRzDvnIneClvRCWCF6vsMC4
        7ARd6LNokvhUhAM006D6GoTrcRvc1yLRWocgMMOGBcmetI1lnDg2g2MiWv+SYhfo
        G258dSOPluqiUJB28g631ufbLrGV1f4PokLbYgX7oAltHgs6vn24C8A4HJAkNhvU
        aAEJAhCHFTnbo1K0CSj6SjC43z+XwX4TXaRRk7DVT428PM2vWsGAUmlLyiyHgYXK
        q3z//Wzo4niqPdInlUZHzM00d1m8HC1rg1YbO9qL/ThC2m9Lzp3HJjPAhApUg85Y
        RZZdHIohveS+
        =dODc
        -----END PGP MESSAGE-----
      fp: FB1D421EB1DB64A1BD36CDE98DC8C2F226861AB7
  unencrypted_suffix: _unencrypted
  version: 3.9.4
