name: Build, Lint, Tests

on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  call-workflow:
    uses: ./.github/workflows/action.yml
    with:
      test-unit: true
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
